# Generated by Django 3.0.7 on 2020-06-16 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bairros',
            new_name='Bairro',
        ),
    ]
