# Generated by Django 3.0.7 on 2020-06-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200616_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='sintomas',
            field=models.ManyToManyField(to='api.Sintoma'),
        ),
    ]
