# Generated by Django 3.0.7 on 2020-06-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_caso_sintomas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='locaisVisitados',
            field=models.ManyToManyField(blank=True, null=True, to='api.Locais'),
        ),
    ]
